name: msvc-dev-cmd

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
      - wip/debugging
  schedule:
    - cron: '0 6 * * *'

jobs:
  test:
    name: default
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '2.7'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Download Internet
        run: npm install
      - name: Enable Developer Command Prompt
        uses: ./
      - name: Compile and run some C code
        shell: cmd
        run: |
          cl.exe hello.c
          hello.exe
